# Generated by Django migration

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('imh_ims', '0003_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='par_min',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Default minimum par level for items in this category',
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name='category',
            name='par_max',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Default maximum par level for items in this category',
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]

