# Generated by Django 5.2.9 on 2025-12-27 21:23

import django.core.validators
from django.db import migrations, models
from django.db import connection


def safe_remove_fields(apps, schema_editor):
    """Safely remove par_min and par_max fields if they exist"""
    db_alias = schema_editor.connection.alias
    with connection.cursor() as cursor:
        # Check what columns exist
        cursor.execute("PRAGMA table_info(imh_ims_stocklevel)")
        columns = [row[1] for row in cursor.fetchall()]
        
        # Only remove if they exist
        if 'par_max' in columns:
            try:
                # For SQLite, we'd need to recreate the table, but since par_max
                # should have been removed in migration 0005, we'll skip if it doesn't exist
                pass
            except Exception:
                pass
        
        if 'par_min' in columns:
            try:
                # par_min should have been renamed to par in migration 0005
                pass
            except Exception:
                pass


def reverse_remove_fields(apps, schema_editor):
    """Reverse operation - would add fields back if needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("imh_ims", "0005_rename_par_min_to_par_remove_par_max"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="modulepermission",
            new_name="imh_ims_mod_module_1b05b6_idx",
            old_name="imh_ims_module_module_8a1b2d_idx",
        ),
        migrations.RenameIndex(
            model_name="userpermission",
            new_name="imh_ims_use_user_id_64c119_idx",
            old_name="imh_ims_user_user_id_9c3d4e_idx",
        ),
        migrations.RunPython(safe_remove_fields, reverse_remove_fields),
        migrations.AddField(
            model_name="stocklevel",
            name="par",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Par level - stock should be maintained above this level",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="countline",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="countsession",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="modulepermission",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequest",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequestline",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="requisition",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="requisitionline",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="stocklevel",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userpermission",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
